INFO 2025-06-29 21:03:45,925 autoreload 3984 7256 Watching for file changes with StatReloader
ERROR 2025-06-29 21:03:58,625 log 3984 11288 Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\generic\base.py", line 98, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\IDAN\alx-backend-graphql_crm\alx-backend-graphql\schema.py", line 2, in <module>
    from crm.schema import Query as CRMQuery, Mutation as CRMMutation
  File "C:\Users\IDAN\alx-backend-graphql_crm\crm\schema.py", line 31, in <module>
    class ProductFilter(FilterSet):
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: sku, stock_quantity
ERROR 2025-06-29 21:03:58,672 basehttp 3984 11288 "GET /graphql HTTP/1.1" 500 149785
WARNING 2025-06-29 21:04:00,052 log 3984 11288 Not Found: /favicon.ico
WARNING 2025-06-29 21:04:00,055 basehttp 3984 11288 "GET /favicon.ico HTTP/1.1" 404 2702
ERROR 2025-06-29 21:05:21,156 log 3984 11288 Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\generic\base.py", line 98, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\IDAN\alx-backend-graphql_crm\alx-backend-graphql\schema.py", line 2, in <module>
    from crm.schema import Query as CRMQuery, Mutation as CRMMutation
  File "C:\Users\IDAN\alx-backend-graphql_crm\crm\schema.py", line 31, in <module>
    class ProductFilter(FilterSet):
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: sku, stock_quantity
ERROR 2025-06-29 21:05:21,188 basehttp 3984 11288 "GET /graphql HTTP/1.1" 500 149791
INFO 2025-06-29 21:07:36,445 basehttp 3984 11276 "GET /graphql HTTP/1.1" 200 2611
INFO 2025-06-29 21:07:36,870 basehttp 3984 11276 "GET /static/graphene_django/graphiql.js HTTP/1.1" 200 4037
INFO 2025-06-29 21:07:38,012 basehttp 3984 11276 "POST /graphql HTTP/1.1" 200 61060
